name: Request to deploy application

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        type: string
        required: true
        default: tst
      account_name:
        description: "Name of AWS account for deployment"
        type: string
        required: true
        default: davincicloud-davinciservices
      software_version:
        description: "Software version to deploy"
        type: string
        required: true
      stack_name:
        description: "Stack name of CloudFormation (if not set - project artifactId)"
        type: string
        required: false
      template_name:
        description: "CloudFormation template name (if not set - project artifactId)"
        type: string
        required: false
      cfg_repo:
        description: "CloudFormation template name (if not set - project artifactId)"
        type: string
        required: false
      REPOSIOTRY_NAME:
        description: "Deployment job repository (change if deployment request is in different repository than deployment workflow)"
        type: string
        required: false
    secrets:
      CICD_GITHUB_WORKFLOW_TOKEN:
        required: true
      REPO_ACCESS_TOKEN:
        required: true

jobs:
  send-deployment-request:
    runs-on: ubuntu-latest
    steps:
      - name: Sending deployment request
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: ${{ inputs.environment }}_deployment_request_event
          repository: vjancich/ermis-app-java
          client-payload: '{
             "environment": "${{ inputs.environment }}",
             "account_name": "${{ inputs.account_name }}",
             "software_version": "${{ inputs.software_version }}",
             "stack_name": "${{ inputs.stack_name }}",
             "template_name": "ermis"
           }'
