name: Trigger deployment

on:
  workflow_call:

jobs:
  check-jira-tickets-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ohpensource/platform-cicd/actions/git/ensure-commits-message-jira-ticket@2.15.0.1
        name: Ensure Jira ticket in all commits
        with:
          base-branch: $GITHUB_BASE_REF
          pr-branch: $GITHUB_HEAD_REF

      - name: Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: https://vladys.atlassian.net
          JIRA_USER_EMAIL: valdo564@azet.sk
          JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}

      - name: Jira
        id: find_commits
        run: |
          echo "base sha je ${{ github.event.pull_request.base.sha }}"
          echo "feature sha je ${{ github.event.pull_request.head.sha }}"
          commits=$(git log --pretty=format:%s $(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})..${{ github.event.pull_request.head.sha }} | sed 's/^/ /'| tr -d '\n' )
          echo "$commits"
          echo "commit_messages=$commits" >> $GITHUB_OUTPUT

      - name: Find in commit messages official
        id: find_jira_issue
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ steps.find_commits.outputs.commit_messages }}

      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.TOKEN_2608 }}
          labels: ${{ steps.find_jira_issue.outputs.issue }}
